/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

CREATE TABLE `wp_GDFormFields` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Form` int(11) unsigned DEFAULT NULL,
  `Label` varchar(100) DEFAULT NULL,
  `LabelPosition` int(11) unsigned NOT NULL DEFAULT '1',
  `Required` int(1) DEFAULT '0',
  `Disabled` int(1) DEFAULT '0',
  `Class` varchar(30) DEFAULT NULL,
  `ContainerClass` varchar(30) DEFAULT NULL,
  `HelperText` text,
  `TypeId` int(11) unsigned DEFAULT '1',
  `DefaultValue` text,
  `Placeholder` varchar(255) DEFAULT NULL,
  `Ordering` int(3) DEFAULT '0',
  `Resizable` int(1) DEFAULT '0',
  `LimitNumber` int(10) DEFAULT '0',
  `LimitType` varchar(4) DEFAULT 'char',
  `LimitText` varchar(100) DEFAULT NULL,
  `Minimum` float DEFAULT '0',
  `Maximum` float DEFAULT '10000',
  `NumberType` varchar(5) DEFAULT 'int',
  `OptionType` varchar(12) DEFAULT NULL,
  `MapCenter` varchar(100) DEFAULT '{lat:48.2222,lng:15.2222}',
  `Draggable` int(1) DEFAULT '1',
  `RecaptchaType` varchar(8) DEFAULT NULL,
  `RecaptchaStyle` varchar(5) DEFAULT NULL,
  `MaskOn` int(1) DEFAULT NULL,
  `MaskPattern` varchar(100) DEFAULT NULL,
  `FileTypes` varchar(255) DEFAULT NULL,
  `UploadSize` int(4) DEFAULT '2',
  `MultipleUpload` int(1) DEFAULT NULL,
  `MinDate` varchar(40) DEFAULT NULL,
  `MaxDate` varchar(40) DEFAULT NULL,
  `DateFormat` varchar(15) DEFAULT 'dd/mm/yy',
  `Height` int(4) DEFAULT NULL,
  `LimitSelected` int(4) DEFAULT NULL,
  `SearchOn` int(1) DEFAULT '1',
  `PasswordViewToggle` int(1) DEFAULT '0',
  PRIMARY KEY (`Id`),
  KEY `Form` (`Form`),
  KEY `LabelPosition` (`LabelPosition`),
  KEY `TypeId` (`TypeId`),
  CONSTRAINT `wp_GDFormFields_ibfk_1` FOREIGN KEY (`Form`) REFERENCES `wp_GDFormForms` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `wp_GDFormFields_ibfk_2` FOREIGN KEY (`LabelPosition`) REFERENCES `wp_GDFormLabelPositions` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `wp_GDFormFields_ibfk_3` FOREIGN KEY (`TypeId`) REFERENCES `wp_GDFormFieldTypes` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;
